#pragma config(Sensor, dgtl12, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//turn LED on and off twice
	/*
	turnLEDOff(greenLED);
	wait(1);
	turnLEDOn(greenLED);
	wait(1);
	turnLEDOff(greenLED);
	wait(1);
	turnLEDOn(greenLED);
	wait(1);
	turnLEDOff(greenLED);
	*/

	//9) starting with motors
	startMotor(rightMotor,64); 	//start motor at 1/2 speed
	wait(5); 										//run motor for 5 seconds
	stopMotor(rightMotor);			//stop motor
}
