#pragma config(Sensor, dgtl12, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//turn LED on and off twice
	/*
	turnLEDOff(greenLED);
	wait(1);
	turnLEDOn(greenLED);
	wait(1);
	turnLEDOff(greenLED);
	wait(1);
	turnLEDOn(greenLED);
	wait(1);
	turnLEDOff(greenLED);
	*/

	//9) starting with motors
	/*
	setMotor(rightMotor, 64);		//start motors at 1/2 speed
	setMotor(leftMotor, 64);
	wait(5); 										//run motors for 5 seconds
	stopMotor(rightMotor);			//stop
	stopMotor(leftMotor);

	setMotor(rightMotor, -64);		//start motors at -1/2 speed
	setMotor(leftMotor, -64);
	wait(5); 										//run motors for 5 seconds
	stopMotor(rightMotor);			//stop
	stopMotor(leftMotor);
	*/

	//15)
	setMotor(rightMotor, 64);
	wait(5);
	stopMotor(rightMotor);
	setMotor(leftMotor, -96);
	wait(2.5);
	stopMotor(leftMotor);
	setMotor(rightMotor, 127);
	setMotor(leftMotor, 127);
	wait(7.25);
	stopMotor(leftMotor);
	stopMotor(rightMotor);



}
