#pragma config(Sensor, in1,    leftLineSensor, sensorLineFollower)
#pragma config(Sensor, in2,    rightLineSensor, sensorLineFollower)
#pragma config(Sensor, dgtl1,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  button,         sensorTouch)
#pragma config(Sensor, dgtl9,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

startMotor(rightMotor, 65);
startMotor(leftMotor, 65);
untilBump(button);
startMotor(leftMotor, 65);
startMotor(rightMotor,-65);
wait(50);
untilBump(button);
stopMotor(rightMotor);
stopMotor(leftMotor);
wait(50);
}
