
#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Motor,  port1,           reset,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port9,           airlock,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RESET_THRESH 80

task main()
{
	// perform airlock functions and whatnot
	// reset color sensor on hang
	setServo(airlock, -46);
	wait(8);
	for (;;)
	{
		float ls = SensorValue(lightSensor);
		if (ls > RESET_THRESH)
			startMotor(reset, -124);
		else
		{
			startMotor(reset, 124);
			waitInMilliseconds(200);
			startMotor(reset, -124);
			wait(5);
		}
		setServo(airlock, 0);
		waitInMilliseconds(75);
		setServo(airlock, -46);
		waitInMilliseconds(2000);

	}

}
