#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Motor,  port1,           reset,         tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RESET_THRESH 60

task main()
{
	// perform airlock functions and whatnot
	// reset color sensor on hang
	for (;;)
	{
		float ls = SensorValue(lightSensor);
		if (ls > RESET_THRESH)
			startMotor(reset, -124);
		else
			startMotor(reset, 124);
	}

}
