#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Motor,  port1,           reset,         tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RESET_MIN 0
#define RESET_MAX 0

task main()
{
	// perform airlock functions and whatnot
	if (SensorValue(lightSensor) > (RESET_MIN + RESET_MAX) / 2)


}
